name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: edoardopanzeri 

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
    
      - name: Build the app
        run: scripts/buildprod.sh

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKERHUB_NAMESPACE }}/notely:latest .

      - name: Run Docker image
        run: docker run -e PORT=8080 -p 8080:8080 ${{ env.DOCKERHUB_NAMESPACE }}/notely:latest
