name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: edoardopanzeri 
      DATABASE_URL: github.com/bootdotdev/learn-cicd-starter/internal/database

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
    
      - name: Build the app
        run: scripts/buildprod.sh

