name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Go version
        uses: actions/go@version
        id: go_version
        env:
          GO_VERSION: ${{ steps.setup-go.outputs.GOVARIANT }}
        run: echo "Go version is $GO_VERSION"
        shell: bash